### ISSUE TITLE
Question: constructor injected Binder vs context.getBinder()

### ISSUE THREAD

**Issue by aalba6675** [philwebb/scratch-boot-gh-32854#1]
In my original question I got confused by the two `Binder`s: https://github.com/spring-projects/spring-boot/issues/32854#issuecomment-1311183256

Could you explain the use case for the constructor-injected `Binder`?

```
MyConfigDataLocationResolver(Log log, Binder binder) {
    super();
    this.log = log;
    this.binder = binder; // this binder doesn't have access to properties like
        // context.getBinder();
        // What is the use case for this parameter?
}
```

**Comment by philwebb** [comment]
The constructor injected binder gives you access to the initial Environment and is useful if you want to offer some kind configuration before resolution begins. For example, we use it in `StandardConfigDataLocationResolver` to pick up `spring.config.name` which changes the name of the loaded files.
